# -*- coding: utf-8 -*-
"""Yet another copy of diabeticRetinoaphyROG

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hGQIFaFdavI4Ir8jdbZL55d1a_Qw0NYU
"""

!pip install torch torchvision Pillow tifffile
# Install the required libraries
#SAM
!pip install git+https://github.com/facebookresearch/segment-anything.git
#Transformers
!pip install -q git+https://github.com/huggingface/transformers.git
!pip install patchify
#Datasets to prepare data and monai for special loss functions
!pip install datasets
!pip install -q monai





import pandas as pd
import numpy as mp
import numpy as np
import matplotlib.pyplot as plt
import tifffile
import os
import random
from scipy import ndimage
from PIL import Image
from patchify import patchify

from google.colab import drive
drive.mount('/content/drive')





###read in images
large_images = []
large_microaneurysms = []
large_hemorrhages = []
large_hard_exudates=[]


for filename in os.listdir("/content/drive/MyDrive/Diabetic Retinopathy/Dataset2/A. Segmentation/1. Original Images/a. Training Set"):
            file_path = os.path.join("/content/drive/MyDrive/Diabetic Retinopathy/Dataset2/A. Segmentation/1. Original Images/a. Training Set", filename)
            # Open image file
            img = Image.open(file_path)
            large_images.append(img)

# display image to veirfy loaded properly
image_array = np.array(large_images[0])
plt.imshow(image_array)
plt.axis('off')
plt.show()

for filename in os.listdir("/content/drive/MyDrive/Diabetic Retinopathy/Dataset2/A. Segmentation/2. All Segmentation Groundtruths/a. Training Set/1. Microaneurysms"):
            file_path = os.path.join("/content/drive/MyDrive/Diabetic Retinopathy/Dataset2/A. Segmentation/2. All Segmentation Groundtruths/a. Training Set/1. Microaneurysms", filename)
                # Open image file
            img = Image.open(file_path)
            large_microaneurysms.append(img)


# display image to veirfy loaded properly
image_array = np.array(large_microaneurysms[0])
# Create a figure and set the background color to black
fig, ax = plt.subplots()
fig.patch.set_facecolor('black')
ax.set_facecolor('black')
# Display the image
ax.imshow(image_array, cmap='gray')  # Use cmap='gray' for grayscale images
ax.axis('off')  # Hide axes for better display
plt.show()

for filename in os.listdir("/content/drive/MyDrive/Diabetic Retinopathy/Dataset2/A. Segmentation/2. All Segmentation Groundtruths/a. Training Set/2. Haemorrhages"):
            file_path = os.path.join("/content/drive/MyDrive/Diabetic Retinopathy/Dataset2/A. Segmentation/2. All Segmentation Groundtruths/a. Training Set/2. Haemorrhages", filename)
                # Open image file
            img = Image.open(file_path)
            large_hemorrhages.append(img)


# display image to veirfy loaded properly
image_array = np.array(large_hemorrhages[0])
# Create a figure and set the background color to black
fig, ax = plt.subplots()
fig.patch.set_facecolor('black')
ax.set_facecolor('black')
# Display the image
ax.imshow(image_array, cmap='gray')  # Use cmap='gray' for grayscale images
ax.axis('off')  # Hide axes for better display
plt.show()

for filename in os.listdir("/content/drive/MyDrive/Diabetic Retinopathy/Dataset2/A. Segmentation/2. All Segmentation Groundtruths/a. Training Set/3. Hard Exudates"):
            file_path = os.path.join("/content/drive/MyDrive/Diabetic Retinopathy/Dataset2/A. Segmentation/2. All Segmentation Groundtruths/a. Training Set/3. Hard Exudates", filename)
                # Open image file
            img = Image.open(file_path)
            large_hard_exudates.append(img)


# display image to veirfy loaded properly
image_array = np.array(large_hard_exudates[0])
# Create a figure and set the background color to black
fig, ax = plt.subplots()
fig.patch.set_facecolor('black')
ax.set_facecolor('black')
# Display the image
ax.imshow(image_array, cmap='gray')  # Use cmap='gray' for grayscale images
ax.axis('off')  # Hide axes for better display
plt.show()


#convert images to gray scale
#large_images = np.mean(large_images, axis=-1)
#large_microaneurysms = np.mean(large_microaneurysms, axis=-1)



#convert images to numpy arrays
large_images = np.array(large_images)
large_microaneurysms = np.array(large_microaneurysms)
large_hemorrhages = np.array(large_hemorrhages)
large_hard_exudates = np.array(large_hard_exudates)

large_images.shape

large_hard_exudates.shape

patch_size = 512
step = 512

all_img_patches = []
for img in range(large_images.shape[0]):
    image = large_images[img]
    patches_img = patchify(image, (patch_size, patch_size,3), step=step)  #Step=256 for 256 patches means no overlap

    for i in range(patches_img.shape[0]):
        for j in range(patches_img.shape[1]):

            single_patch_img = patches_img[i,j,:,:]
            all_img_patches.append(single_patch_img)

unfiltered_images = np.array(all_img_patches)
unfiltered_images = np.reshape(unfiltered_images, (2120, 512, 512, 3))
#Let us do the same for masks
all_mask_patches = []
for img in range(large_microaneurysms.shape[0]):
    large_mask = large_microaneurysms[img]
    patches_mask = patchify(large_mask, (patch_size, patch_size), step=step)  #Step=256 for 256 patches means no overlap

    for i in range(patches_mask.shape[0]):
        for j in range(patches_mask.shape[1]):

            single_patch_mask = patches_mask[i,j,:,:]
            #single_patch_mask = (single_patch_mask / 255.).astype(np.uint8)
            all_mask_patches.append(single_patch_mask)

all_mask1_patches = []
for img in range(large_hemorrhages.shape[0]):
    large_mask = large_hemorrhages[img]
    patches_mask = patchify(large_mask, (patch_size, patch_size), step=step)  #Step=256 for 256 patches means no overlap

    for i in range(patches_mask.shape[0]):
        for j in range(patches_mask.shape[1]):

            single_patch_mask = patches_mask[i,j,:,:]
            #single_patch_mask = (single_patch_mask / 255.).astype(np.uint8)
            all_mask1_patches.append(single_patch_mask)

all_mask2_patches = []
for img in range(large_hard_exudates.shape[0]):
    large_mask = large_hard_exudates[img]
    patches_mask = patchify(large_mask, (patch_size, patch_size), step=step)  #Step=256 for 256 patches means no overlap

    for i in range(patches_mask.shape[0]):
        for j in range(patches_mask.shape[1]):

            single_patch_mask = patches_mask[i,j,:,:]
            #single_patch_mask = (single_patch_mask / 255.).astype(np.uint8)
            all_mask2_patches.append(single_patch_mask)

microaneurysms = np.array(all_mask_patches)
hemorrhages = np.array(all_mask1_patches)
hard_exudates = np.array(all_mask2_patches)

unfiltered_images.shape

hemorrhages.shape

hard_exudates.shape

# Create a list to store the indices of non-empty masks
valid_indices = [i for i, mask in enumerate(microaneurysms) if mask.max() != 0]
# Filter the image and mask arrays to keep only the non-empty pairs
images = unfiltered_images[valid_indices]
microaneurysms = microaneurysms[valid_indices]

valid_indices1 = [i for i, mask in enumerate(hemorrhages) if mask.max() != 0]
# Filter the image and mask arrays to keep only the non-empty pairs
hemorrhages = hemorrhages[valid_indices1]
images_hemorrhages = unfiltered_images[valid_indices1]

valid_indices2 = [i for i, mask in enumerate(hard_exudates) if mask.max() != 0]
# Filter the image and mask arrays to keep only the non-empty pairs
hard_exudates = hard_exudates[valid_indices2]
images_hard_exudates = unfiltered_images[valid_indices2]



print("Image shape:", images.shape)  # e.g., (num_frames, height, width, num_channels)
print("Mask shape:", microaneurysms.shape)
print("Image shape:", images_hemorrhages.shape)
print("Mask shape:", hemorrhages.shape)
print("Image shape:", images_hard_exudates.shape)
print("Mask shape:", hard_exudates.shape)

from datasets import Dataset
from PIL import Image

# Convert the NumPy arrays to Pillow images and store them in a dictionary
dataset_dict = {
    "image": [Image.fromarray(img) for img in images],
    "label": [Image.fromarray(mask) for mask in microaneurysms],
}

# Create the dataset using the datasets.Dataset class
dataset = Dataset.from_dict(dataset_dict)

dataset_dict_hemorrhages = {
    "image": [Image.fromarray(img) for img in images_hemorrhages],
    "label": [Image.fromarray(mask) for mask in hemorrhages],
}

dataset_hemorrhages= Dataset.from_dict(dataset_dict_hemorrhages)

dataset_dict_hard_exudates = {
    "image": [Image.fromarray(img) for img in images_hard_exudates],
    "label": [Image.fromarray(mask) for mask in hard_exudates],
}

dataset_hard_exudates= Dataset.from_dict(dataset_dict_hard_exudates)



dataset_hemorrhages

# verify images are loading properly
img_num = random.randint(0, images_hemorrhages.shape[0]-1)
example_image = dataset[img_num]["image"]
example_mask = dataset[img_num]["label"]



fig, axes = plt.subplots(1, 2, figsize=(10, 5))

# Plot the first image on the left
axes[0].imshow(np.array(example_image), cmap='gray')  # Assuming the first image is grayscale
axes[0].set_title("Image")

# Plot the second image on the right
axes[1].imshow(example_mask, cmap='gray')  # Assuming the second image is grayscale
axes[1].set_title("Mask")

# Hide axis ticks and labels
for ax in axes:
    ax.set_xticks([])
    ax.set_yticks([])
    ax.set_xticklabels([])
    ax.set_yticklabels([])

# Display the images side by side
plt.show()

example_image = dataset_hemorrhages[img_num]["image"]
example_mask = dataset_hemorrhages[img_num]["label"]
fig, axes = plt.subplots(1, 2, figsize=(10, 5))

# Plot the first image on the left
axes[0].imshow(np.array(example_image), cmap='gray')  # Assuming the first image is grayscale
axes[0].set_title("Image")

# Plot the second image on the right
axes[1].imshow(example_mask, cmap='gray')  # Assuming the second image is grayscale
axes[1].set_title("Mask")

# Hide axis ticks and labels
for ax in axes:
    ax.set_xticks([])
    ax.set_yticks([])
    ax.set_xticklabels([])
    ax.set_yticklabels([])

# Display the images side by side
plt.show()

example_image = dataset_hard_exudates[img_num]["image"]
example_mask = dataset_hard_exudates[img_num]["label"]
fig, axes = plt.subplots(1, 2, figsize=(10, 5))

# Plot the first image on the left
axes[0].imshow(np.array(example_image), cmap='gray')  # Assuming the first image is grayscale
axes[0].set_title("Image")

# Plot the second image on the right
axes[1].imshow(example_mask, cmap='gray')  # Assuming the second image is grayscale
axes[1].set_title("Mask")

# Hide axis ticks and labels
for ax in axes:
    ax.set_xticks([])
    ax.set_yticks([])
    ax.set_xticklabels([])
    ax.set_yticklabels([])

# Display the images side by side
plt.show()







#Get bounding boxes from mask.
def get_bounding_box(ground_truth_map):
  # get bounding box from mask
  y_indices, x_indices = np.where(ground_truth_map > 0)
  x_min, x_max = np.min(x_indices), np.max(x_indices)
  y_min, y_max = np.min(y_indices), np.max(y_indices)
  # add perturbation to bounding box coordinates
  H, W = ground_truth_map.shape
  x_min = max(0, x_min - np.random.randint(0, 20))
  x_max = min(W, x_max + np.random.randint(0, 20))
  y_min = max(0, y_min - np.random.randint(0, 20))
  y_max = min(H, y_max + np.random.randint(0, 20))
  bbox = [x_min, y_min, x_max, y_max]

  return bbox

from torch.utils.data import Dataset

class SAMDataset(Dataset):
  """
  This class is used to create a dataset that serves input images and masks.
  It takes a dataset and a processor as input and overrides the __len__ and __getitem__ methods of the Dataset class.
  """
  def __init__(self, dataset, processor):
    self.dataset = dataset
    self.processor = processor

  def __len__(self):
    return len(self.dataset)

  def __getitem__(self, idx):
    item = self.dataset[idx]
    image = item["image"]
    ground_truth_mask = np.array(item["label"])

    # get bounding box prompt
    prompt = get_bounding_box(ground_truth_mask)

    # prepare image and prompt for the model
    inputs = self.processor(image, input_boxes=[[prompt]], return_tensors="pt")

    # remove batch dimension which the processor adds by default
    inputs = {k:v.squeeze(0) for k,v in inputs.items()}

    # add ground truth segmentation
    inputs["ground_truth_mask"] = ground_truth_mask

    return inputs

# Initialize the processor
from transformers import SamProcessor
processor = SamProcessor.from_pretrained("facebook/sam-vit-base")

"""TRAIN MODEL FOR MICROANEURYSMS


"""

# Create an instance of the SAMDataset
train_dataset = SAMDataset(dataset=dataset, processor=processor)

"""TRAIN MODEL FOR HEMORRHAGES"""

train_dataset = SAMDataset(dataset=dataset_hemorrhages, processor=processor)

"""TRAIN MODEL FOR HARD EXUDATES"""

train_dataset = SAMDataset(dataset=dataset_hard_exudates, processor=processor)

"""MODEL TRAINING FOR ANY FEATURE"""

# Create a DataLoader instance for the training dataset
from torch.utils.data import DataLoader
train_dataloader = DataLoader(train_dataset, batch_size=2, shuffle=True, drop_last=False)

# Load the model
from transformers import SamModel
model = SamModel.from_pretrained("facebook/sam-vit-base")

# make sure we only compute gradients for mask decoder
for name, param in model.named_parameters():
  if name.startswith("vision_encoder") or name.startswith("prompt_encoder"):
    param.requires_grad_(False)

from torch.optim import Adam
import monai
# Initialize the optimizer and the loss function
optimizer = Adam(model.mask_decoder.parameters(), lr=1e-5, weight_decay=0)
#Try DiceFocalLoss, FocalLoss, DiceCELoss
seg_loss = monai.losses.DiceCELoss(sigmoid=True, squared_pred=True, reduction='mean')

from tqdm import tqdm
from statistics import mean
import torch
from torch.nn.functional import threshold, normalize
import torch.nn.functional as F
from torch import nn



#Training loop
num_epochs = 30

device = "cuda" if torch.cuda.is_available() else "cpu"
model.to(device)

model.train()
for epoch in range(num_epochs):
    epoch_losses = []
    for batch in tqdm(train_dataloader):
      # forward pass
      outputs = model(pixel_values=batch["pixel_values"].to(device),
                      input_boxes=batch["input_boxes"].to(device),
                      multimask_output=False)

      # compute loss
      predicted_masks = outputs.pred_masks.squeeze(1)
      predicted_masks = nn.functional.interpolate(predicted_masks,
                size=(512,512),
                mode='bilinear',
                align_corners=False)
      ground_truth_masks = batch["ground_truth_mask"].float().to(device)
      loss = seg_loss(predicted_masks, ground_truth_masks.unsqueeze(1))

      # backward pass (compute gradients of parameters w.r.t. loss)
      optimizer.zero_grad()
      loss.backward()

      # optimize
      optimizer.step()
      epoch_losses.append(loss.item())

    print(f'EPOCH: {epoch}')
    print(f'Mean loss: {mean(epoch_losses)}')

"""Save model hemorrhages"""

torch.save(model.state_dict(), "/content/drive/MyDrive/Diabetic Retinopathy/hemorrhages.pth")

"""Save model hard exudates"""

torch.save(model.state_dict(), "/content/drive/MyDrive/Diabetic Retinopathy/hard exudates.pth")

"""INFERENCE"""

from transformers import SamModel, SamConfig, SamProcessor
import torch

# Load the model configuration
model_config = SamConfig.from_pretrained("facebook/sam-vit-base")
processor = SamProcessor.from_pretrained("facebook/sam-vit-base")

# Create an instance of the model architecture with the loaded configuration
my_mito_model = SamModel(config=model_config)
#Update the model by loading the weights from saved file.
my_mito_model.load_state_dict(torch.load( "/content/drive/MyDrive/Diabetic Retinopathy/microaneurysms.pth"))

# set the device to cuda if available, otherwise use cpu
device = "cuda" if torch.cuda.is_available() else "cpu"
my_mito_model.to(device)

import numpy as np
import random
import torch
import matplotlib.pyplot as plt

# let's take a random training example
for idx in range(dataset.shape[0]):

  # load image
  test_image = dataset[idx]["image"]

  # get box prompt based on ground truth segmentation map
  ground_truth_mask = np.array(dataset[idx]["label"])
  prompt = get_bounding_box(ground_truth_mask)

  # prepare image + box prompt for the model
  inputs = processor(test_image, input_boxes=[[prompt]], return_tensors="pt")

  # Move the input tensor to the GPU if it's not already there
  inputs = {k: v.to(device) for k, v in inputs.items()}

  my_mito_model.eval()

  # forward pass
  with torch.no_grad():
      outputs = my_mito_model(**inputs, multimask_output=False)

  # apply sigmoid
  medsam_seg_prob = torch.sigmoid(outputs.pred_masks.squeeze(1))
  # convert soft mask to hard mask
  medsam_seg_prob = medsam_seg_prob.cpu().numpy().squeeze()
  medsam_seg = (medsam_seg_prob > 0.15).astype(np.uint8)


  fig, axes = plt.subplots(1, 3, figsize=(15, 5))

  # Plot the first image on the left
  axes[0].imshow(np.array(test_image), cmap='gray')  # Assuming the first image is grayscale
  axes[0].set_title("Image")

  # Plot the second image on the right
  axes[1].imshow(medsam_seg, cmap='gray')  # Assuming the second image is grayscale
  axes[1].set_title("Mask")

  # Plot the second image on the right
  axes[2].imshow(medsam_seg_prob)  # Assuming the second image is grayscale
  axes[2].set_title("Probability Map")

  # Hide axis ticks and labels
  for ax in axes:
      ax.set_xticks([])
      ax.set_yticks([])
      ax.set_xticklabels([])
      ax.set_yticklabels([])

  # Display the images side by side
  plt.show()

"""VALIDATION"""

validation_images = []
validation_microaneurysms = []
validation_hemorrhages = []
validation_hard_exudates=[]

for filename in os.listdir("/content/drive/MyDrive/Diabetic Retinopathy/Dataset2/A. Segmentation/1. Original Images/b. Testing Set"):
            file_path = os.path.join("/content/drive/MyDrive/Diabetic Retinopathy/Dataset2/A. Segmentation/1. Original Images/b. Testing Set", filename)
            # Open image file
            img = Image.open(file_path)
            validation_images.append(img)

# display image to veirfy loaded properly
image_array = np.array(validation_images[0])
plt.imshow(image_array)
plt.axis('off')
plt.show()

for filename in os.listdir("/content/drive/MyDrive/Diabetic Retinopathy/Dataset2/A. Segmentation/2. All Segmentation Groundtruths/b. Testing Set/1. Microaneurysms"):
            file_path = os.path.join("/content/drive/MyDrive/Diabetic Retinopathy/Dataset2/A. Segmentation/2. All Segmentation Groundtruths/b. Testing Set/1. Microaneurysms", filename)
                # Open image file
            img = Image.open(file_path)
            validation_microaneurysms.append(img)


# display image to veirfy loaded properly
image_array = np.array(validation_microaneurysms[0])
# Create a figure and set the background color to black
fig, ax = plt.subplots()
fig.patch.set_facecolor('black')
ax.set_facecolor('black')
# Display the image
ax.imshow(image_array, cmap='gray')  # Use cmap='gray' for grayscale images
ax.axis('off')  # Hide axes for better display
plt.show()

for filename in os.listdir("/content/drive/MyDrive/Diabetic Retinopathy/Dataset2/A. Segmentation/2. All Segmentation Groundtruths/b. Testing Set/2. Haemorrhages"):
            file_path = os.path.join("/content/drive/MyDrive/Diabetic Retinopathy/Dataset2/A. Segmentation/2. All Segmentation Groundtruths/b. Testing Set/2. Haemorrhages", filename)
                # Open image file
            img = Image.open(file_path)
            validation_hemorrhages.append(img)


# display image to veirfy loaded properly
image_array = np.array(validation_hemorrhages[0])
# Create a figure and set the background color to black
fig, ax = plt.subplots()
fig.patch.set_facecolor('black')
ax.set_facecolor('black')
# Display the image
ax.imshow(image_array, cmap='gray')  # Use cmap='gray' for grayscale images
ax.axis('off')  # Hide axes for better display
plt.show()

for filename in os.listdir("/content/drive/MyDrive/Diabetic Retinopathy/Dataset2/A. Segmentation/2. All Segmentation Groundtruths/b. Testing Set/3. Hard Exudates"):
            file_path = os.path.join("/content/drive/MyDrive/Diabetic Retinopathy/Dataset2/A. Segmentation/2. All Segmentation Groundtruths/b. Testing Set/3. Hard Exudates", filename)
                # Open image file
            img = Image.open(file_path)
            validation_hard_exudates.append(img)


# display image to veirfy loaded properly
image_array = np.array(validation_hard_exudates[0])
# Create a figure and set the background color to black
fig, ax = plt.subplots()
fig.patch.set_facecolor('black')
ax.set_facecolor('black')
# Display the image
ax.imshow(image_array, cmap='gray')  # Use cmap='gray' for grayscale images
ax.axis('off')  # Hide axes for better display
plt.show()


#convert images to gray scale
#large_images = np.mean(large_images, axis=-1)
#large_microaneurysms = np.mean(large_microaneurysms, axis=-1)



#convert images to numpy arrays
validation_images = np.array(validation_images)
validation_microaneurysms = np.array(validation_microaneurysms)
validation_hemorrhages = np.array(validation_hemorrhages)
validation_hard_exudates = np.array(validation_hard_exudates)

validation_images.shape

from datasets import Dataset
from PIL import Image

# Convert the NumPy arrays to Pillow images and store them in a dictionary
dataset_dict1 = {
    "image": [Image.fromarray(img) for img in validation_images],
    "label": [Image.fromarray(mask) for mask in validation_microaneurysms],
}

# Create the dataset using the datasets.Dataset class
validation_dataset_microaneurysms = Dataset.from_dict(dataset_dict1)
print(validation_dataset_microaneurysms.shape)

dataset_dict2 = {
    "image": [Image.fromarray(img) for img in validation_images],
    "label": [Image.fromarray(mask) for mask in validation_hemorrhages],
}

validation_dataset_hemorrhages= Dataset.from_dict(dataset_dict2)

dataset_dict3 = {
    "image": [Image.fromarray(img) for img in validation_images],
    "label": [Image.fromarray(mask) for mask in validation_hard_exudates],
}

validation_dataset_hard_exudates= Dataset.from_dict(dataset_dict3)

"""BEGIN VALIDATION TESTING"""

from transformers import SamModel, SamConfig, SamProcessor
import torch

# Load the model configuration
model_config = SamConfig.from_pretrained("facebook/sam-vit-base")
processor = SamProcessor.from_pretrained("facebook/sam-vit-base")

# Create an instance of the model architecture with the loaded configuration
my_mito_model = SamModel(config=model_config)

"""LOAD MICROANEURYSMS DETECTION MODEL"""

#Update the model by loading the weights from saved file.
my_mito_model.load_state_dict(torch.load( "/content/drive/MyDrive/Diabetic Retinopathy/microaneurysms.pth"))

"""LOAD HEMORRHAGES DETECTION MODEL"""

#Update the model by loading the weights from saved file.
my_mito_model.load_state_dict(torch.load( "/content/drive/MyDrive/Diabetic Retinopathy/hemorrhages.pth"))

"""LOAD HARD EXUDATES DETECTION MODEL"""

#Update the model by loading the weights from saved file.
my_mito_model.load_state_dict(torch.load( "/content/drive/MyDrive/Diabetic Retinopathy/hard exudates.pth"))

"""VALIDATION TESTING"""

# set the device to cuda if available, otherwise use cpu
device = "cuda" if torch.cuda.is_available() else "cpu"
my_mito_model.to(device)

import numpy as np
import random
import torch
import matplotlib.pyplot as plt

"""GENERATE VALIDATION IMAGE SET FOR *MICROANEURYSMS*"""

for idx in range(validation_images.shape[0]):
   # load image
   test_image = validation_dataset_microaneurysms[idx]["image"]

    # get box prompt based on ground truth segmentation map
   ground_truth_mask = np.array(validation_dataset_microaneurysms[idx]["label"])
   prompt = get_bounding_box(ground_truth_mask)

    # prepare image + box prompt for the model
   inputs = processor(test_image, input_boxes=[[prompt]], return_tensors="pt")

    # Move the input tensor to the GPU if it's not already there
   inputs = {k: v.to(device) for k, v in inputs.items()}

   my_mito_model.eval()

    # forward pass
   with torch.no_grad():
       outputs = my_mito_model(**inputs, multimask_output=False)

    # apply sigmoid
   medsam_seg_prob = torch.sigmoid(outputs.pred_masks.squeeze(1))
    # convert soft mask to hard mask
   medsam_seg_prob = medsam_seg_prob.cpu().numpy().squeeze()
   medsam_seg = (medsam_seg_prob > 0.25).astype(np.uint8)

   fig, axes = plt.subplots(1, 3, figsize=(15, 5))

    # Plot the original image on the left
   axes[0].imshow(np.array(test_image), cmap='gray')  # Assuming the first image is grayscale
   axes[0].set_title("Image")

    # Plot the ground truth map
   axes[1].imshow(medsam_seg, cmap='gray')  # Assuming the second image is grayscale
   axes[1].set_title("Mask")

    # Plot the predicted image
   axes[2].imshow(medsam_seg_prob)  # Assuming the second image is grayscale
   axes[2].set_title("Probability Map")

    # Hide axis ticks and labels
   for ax in axes:
       ax.set_xticks([])
       ax.set_yticks([])
       ax.set_xticklabels([])
       ax.set_yticklabels([])

    # Display the images side by side
   plt.show()

"""GENERATE VALIDATION IMAGE SET FOR *HEMORRHAGES*"""

for idx in range(validation_images.shape[0]):
   # load image
   test_image = validation_dataset_hemorrhages[idx]["image"]

    # get box prompt based on ground truth segmentation map
   ground_truth_mask = np.array(validation_dataset_hemorrhages[idx]["label"])
   prompt = get_bounding_box(ground_truth_mask)

    # prepare image + box prompt for the model
   inputs = processor(test_image, input_boxes=[[prompt]], return_tensors="pt")

    # Move the input tensor to the GPU if it's not already there
   inputs = {k: v.to(device) for k, v in inputs.items()}

   my_mito_model.eval()

    # forward pass
   with torch.no_grad():
       outputs = my_mito_model(**inputs, multimask_output=False)

    # apply sigmoid
   medsam_seg_prob = torch.sigmoid(outputs.pred_masks.squeeze(1))
    # convert soft mask to hard mask
   medsam_seg_prob = medsam_seg_prob.cpu().numpy().squeeze()
   medsam_seg = (medsam_seg_prob > 0.25).astype(np.uint8)

   fig, axes = plt.subplots(1, 3, figsize=(15, 5))

    # Plot the original image on the left
   axes[0].imshow(np.array(test_image), cmap='gray')  # Assuming the first image is grayscale
   axes[0].set_title("Image")

    # Plot the ground truth map
   axes[1].imshow(medsam_seg, cmap='gray')  # Assuming the second image is grayscale
   axes[1].set_title("Mask")

    # Plot the predicted image
   axes[2].imshow(medsam_seg_prob)  # Assuming the second image is grayscale
   axes[2].set_title("Probability Map")

    # Hide axis ticks and labels
   for ax in axes:
       ax.set_xticks([])
       ax.set_yticks([])
       ax.set_xticklabels([])
       ax.set_yticklabels([])

    # Display the images side by side
   plt.show()



"""

```
# This is formatted as code
```

GENERATE VALIDATION IMAGE SET FOR *HARD EXUDATES*"""

for idx in range(validation_images.shape[0]):
   # load image
   test_image = validation_dataset_hard_exudates[idx]["image"]

    # get box prompt based on ground truth segmentation map
   ground_truth_mask = np.array(validation_dataset_hard_exudates[idx]["label"])
   prompt = get_bounding_box(ground_truth_mask)

    # prepare image + box prompt for the model
   inputs = processor(test_image, input_boxes=[[prompt]], return_tensors="pt")

    # Move the input tensor to the GPU if it's not already there
   inputs = {k: v.to(device) for k, v in inputs.items()}

   my_mito_model.eval()

    # forward pass
   with torch.no_grad():
       outputs = my_mito_model(**inputs, multimask_output=False)

    # apply sigmoid
   medsam_seg_prob = torch.sigmoid(outputs.pred_masks.squeeze(1))
    # convert soft mask to hard mask
   medsam_seg_prob = medsam_seg_prob.cpu().numpy().squeeze()
   medsam_seg = (medsam_seg_prob > 0.25).astype(np.uint8)


   fig, axes = plt.subplots(1, 3, figsize=(15, 5))

    # Plot the original image on the left
   axes[0].imshow(np.array(test_image), cmap='gray')  # Assuming the first image is grayscale
   axes[0].set_title("Image")

    # Plot the ground truth map
   axes[1].imshow(medsam_seg, cmap='gray')  # Assuming the second image is grayscale
   axes[1].set_title("Mask")

    # Plot the predicted image
   axes[2].imshow(medsam_seg_prob)  # Assuming the second image is grayscale
   axes[2].set_title("Probability Map")

    # Hide axis ticks and labels
   for ax in axes:
       ax.set_xticks([])
       ax.set_yticks([])
       ax.set_xticklabels([])
       ax.set_yticklabels([])

    # Display the images side by side
   plt.show()

from datasets import Dataset
from PIL import Image

# Convert the NumPy arrays to Pillow images and store them in a dictionary
dataset_dict10 = {
    "image": [Image.fromarray(img) for img in large_images],
    "label": [Image.fromarray(mask) for mask in large_hard_exudates],
}

# Create the dataset using the datasets.Dataset class
dataset10 = Dataset.from_dict(dataset_dict10)

import cv2
for idx in range(52):
   # load image
   test_image = dataset10[idx]["image"]

    # get box prompt based on ground truth segmentation map
   ground_truth_mask = np.array(dataset10[idx]["label"])
   prompt = get_bounding_box(ground_truth_mask)

    # prepare image + box prompt for the model
   inputs = processor(test_image, input_boxes=[[prompt]], return_tensors="pt")

    # Move the input tensor to the GPU if it's not already there
   inputs = {k: v.to(device) for k, v in inputs.items()}

   my_mito_model.eval()

    # forward pass
   with torch.no_grad():
       outputs = my_mito_model(**inputs, multimask_output=False)

    # apply sigmoid
   medsam_seg_prob = torch.sigmoid(outputs.pred_masks.squeeze(1))
    # convert soft mask to hard mask
   medsam_seg_prob = medsam_seg_prob.cpu().numpy().squeeze()
   medsam_seg = (medsam_seg_prob > 0.5).astype(np.uint8)
   medsam_seg = Image.fromarray(medsam_seg)
   medsam_seg.save(f'/content/drive/MyDrive/Diabetic Retinopathy/SAM trained masks/SAM hard exudate masks{idx}.png')
  # cv2.imwrite(f'/content/drive/MyDrive/Diabetic Retinopathy/SAM trained masks/SAM hard exudate masks{idx}.png',medsam_seg_prob)

"""cnn"""

!pip install numpy matplotlib torch torchvision

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import transforms, datasets
from torch.utils.data import DataLoader

class RogCNN(nn.Module):
    def __init__(self, num_classes=5):  # Assuming 5 classes for disease grading, but have lens func anyways
        super(RogCNN, self).__init__()
        self.conv1 = nn.Conv2d(3, 32, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(32, 64, kernel_size=3, padding=1)
        self.conv3 = nn.Conv2d(64, 128, kernel_size=3, padding=1)
        self.fc1 = nn.Linear(128 * 16 * 16, 512)
        self.fc2 = nn.Linear(512, num_classes)
        self.pool = nn.MaxPool2d(2, 2)
        self.relu = nn.ReLU()

    def forward(self, x):
        x = self.pool(self.relu(self.conv1(x)))
        x = self.pool(self.relu(self.conv2(x)))
        x = self.pool(self.relu(self.conv3(x)))
        x = x.view(x.size(0), -1)  # Flatten tensor
        x = self.relu(self.fc1(x))
        x = self.fc2(x)
        return x

import pandas as pd
import os

# Load the dataset labels
labels_df = pd.read_csv('/content/drive/MyDrive/Diabetic Retinopathy/Dataset2/B. Disease Grading/2. Groundtruths/a. Edited Training Labels - a. IDRiD_Disease Grading_Training Labels.csv')

# Map filenames to labels
label_map = {row['Image name']: row['Retinopathy grade'] for index, row in labels_df.iterrows()}
#print(label_map)
# Create a custom dataset class to handle image loading and label association
from torchvision.datasets import ImageFolder
from torchvision import transforms
from torch.utils.data import Dataset
from PIL import Image

class CustomDataset(Dataset):
    def __init__(self, img_dir, label_map, transform=None):
        self.img_dir = img_dir
        self.label_map = label_map
        self.transform = transform
        self.images = [f for f in os.listdir(img_dir) if os.path.isfile(os.path.join(img_dir, f))]

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        img_name = self.images[idx]
        img_path = os.path.join(self.img_dir, img_name)
        image = Image.open(img_path).convert('RGB')
        label = self.label_map.get(img_name)
        if label is None:
            print(f"Label for {img_name} not found. Skipping...")
            return None  # This should be handled by checking in the DataLoader
        if self.transform:
            image = self.transform(image)
        return image, label

# Define transformations and create dataset
transform = transforms.Compose([
    transforms.Resize((128, 128)),  # Resize images to 128x128
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])

train_dataset = CustomDataset('/content/drive/MyDrive/Diabetic Retinopathy/Dataset2/B. Disease Grading/1. Original Images/a. Training Set', label_map, transform)
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

# Define a transformation for the input data
transform = transforms.Compose([
    transforms.Resize((128, 128)),  # Resize images
    transforms.ToTensor(),  # Convert images to tensor
    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))  # Normalize images
])

# Assuming the dataset directory structure is suitable for ImageFolder
dataset = datasets.ImageFolder(root= "/content/drive/MyDrive/Diabetic Retinopathy/Dataset2/A. Segmentation/2. All Segmentation Groundtruths/a. Training Set" , transform=transform)
dataloader = DataLoader(dataset, batch_size=32, shuffle=True)

# Initialize ROG model!!!
num_classes = len(dataset.classes)
model = RogCNN(num_classes=num_classes)

# Set device for training
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

# Define loss function and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Training loop
num_epochs = 5
for epoch in range(num_epochs):
    for inputs, labels in dataloader:
        #print(inputs)
        #print(labels)
        inputs, labels = inputs.to(device), labels.to(device)
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
    print(f'Epoch {epoch+1}, Loss: {loss.item()}')

# Set device for training
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = RogCNN(num_classes=5).to(device)

# Define the loss function and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Training loop
num_epochs = 15
for epoch in range(num_epochs):
    running_loss = 0.0
    for inputs, labels in train_loader:
        inputs, labels = inputs.to(device), labels.to(device)
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        running_loss += loss.item()
    print(f'Epoch {epoch+1}, Loss: {running_loss / len(train_loader)}')

import torch
from sklearn.metrics import precision_score, recall_score, accuracy_score

def compute_metrics(preds, labels):
    """
    Compute precision, recall, and accuracy from predictions and labels.
    """
    preds = preds.cpu().numpy()
    labels = labels.cpu().numpy()

    precision = precision_score(labels, preds, average='macro')  # You can change average mode
    recall = recall_score(labels, preds, average='macro')  # You can change average mode
    accuracy = accuracy_score(labels, preds)

    return precision, recall, accuracy

# Assuming you have a test_loader set up for evaluating the model
model.eval()  # Set the model to evaluation mode
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

all_preds = []
all_labels = []

with torch.no_grad():
    for inputs, labels in train_loader:
        inputs = inputs.to(device)
        labels = labels.to(device)
        outputs = model(inputs)
        _, preds = torch.max(outputs, 1)

        all_preds.extend(preds.view(-1))
        all_labels.extend(labels.view(-1))

# Compute metrics
precision, recall, accuracy = compute_metrics(torch.stack(all_preds), torch.stack(all_labels))
print(f"Precision: {precision:.4f}, Recall: {recall:.4f}, Accuracy: {accuracy:.4f}")

import torch

def calculate_accuracy(outputs, labels):
    _, predicted = torch.max(outputs.data, 1)
    correct = (predicted == labels).sum().item()
    total = labels.size(0)
    return 100 * correct / total

# Assuming 'train_loader' is your DataLoader for the training data
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = RogCNN(num_classes=5).to(device)
model.eval()  # Set the model to evaluation mode

total_accuracy = 0
with torch.no_grad():
    for inputs, labels in train_loader:
        inputs, labels = inputs.to(device), labels.to(device)
        outputs = model(inputs)
        total_accuracy += calculate_accuracy(outputs, labels)

average_accuracy = total_accuracy / len(train_loader)
print(f'Training Data Accuracy: {average_accuracy:.2f}%')

model_path = '/content/drive/MyDrive/Diabetic Retinopathy/model.pth'  # Specify the path to save your model
torch.save(model.state_dict(), model_path)

import torch
from sklearn.metrics import precision_score, recall_score, accuracy_score
from torchvision import transforms
from torchvision.datasets import ImageFolder
from torch.utils.data import DataLoader

# Assuming you have a function `RogCNN` that returns a CNN model
model = RogCNN(num_classes=5).to(device)
model.load_state_dict(torch.load('/content/drive/MyDrive/Diabetic Retinopathy/model.pth'))  # Load your trained model weights
model.eval()

# Setup DataLoader for the testing dataset
transform = transforms.Compose([
    transforms.Resize((128, 128)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

test_dataset = CustomDataset('/content/drive/MyDrive/Diabetic Retinopathy/Dataset2/B. Disease Grading/1. Original Images/b. Testing Set', label_map, transform)
test_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

# Initialize lists to store predictions and true labels
all_preds = []
all_labels = []

with torch.no_grad():
    for inputs, labels in test_loader:
        inputs, labels = inputs.to(device), labels.to(device)
        outputs = model(inputs)
        _, preds = torch.max(outputs, 1)

        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

# Calculate precision, recall, and accuracy
precision = precision_score(all_labels, all_preds, average='macro')
recall = recall_score(all_labels, all_preds, average='macro')
accuracy = accuracy_score(all_labels, all_preds)

print(f'Precision: {precision:.4f}, Recall: {recall:.4f}, Accuracy: {accuracy:.4f}')